# Generated by Django 3.1.3 on 2020-11-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20201111_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sub_title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
